### ISSUE TITLE
[Suggestion]: Damage over time should not interrupt eating

### ISSUE THREAD

**Issue by squimbo** [Fuzss/combatnouveau#10]
### Mod Loader (Optional)

⸺

### Suggestion (Required)

I feel that damage over time effects (poison, wither, fire, etc) are too powerful with eating interruption. I think there should be a config option to disable interruption for damage like this, that isn't directly caused by an attack.

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by Fuzss** [comment]
It would probably be worth introducing a damage type tag for controlling which types are intended to to interrupt eating. 

For now you can disable the behavior as a whole in the config.

**Comment by Fuzss** [comment]
Added in 1.21 port.
