### ISSUE TITLE
[Bug]: Can't Throw Snowballs/Eggs

### ISSUE THREAD

**Issue by PpDog27** [Fuzss/combatnouveau#2]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

v20.4.1

### Minimal Setup (Required)

Yes

### Notes (Required)

Snowballs and eggs can not be thrown.

### latest.log (Required)

https://gist.github.com/PpDog27/e9c298d542dc5fda1aa3416fe3d31a8c

**Comment by Fuzss** [comment]
Thanks fixed in v20.4.2.
