### ISSUE TITLE
[Bug]: Combat Nouveau crashes with Biome Makeover, JEI is also broken

### ISSUE THREAD

**Issue by BugmanBugman** [Fuzss/combatnouveau#3]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

8.0.2

### Minimal Setup (Required)

Yes

### Notes (Required)

1. Install the 2 mods together with their respective libraries
2. Load into creative or whatever, look up ite
ms on JEI (notice they're broken)
3. If you get a biome makeover item, it crashes sometimes 
![2024-02-11_15 27 15](https://github.com/Fuzss/combatnouveau/assets/40730042/814e8923-4c34-4d4a-97bc-dfd5e17cb0f6)

### latest.log (Required)

https://gist.github.com/BugmanBugman/67f579ea386943ade3dadc6dccdbd4ed

**Comment by Fuzss** [comment]
Thanks, fixed in v8.0.3.
