### ISSUE TITLE
[Bug]: Impossible to set negative value for attack speed overrides

### ISSUE THREAD

**Issue by MelonCode** [Fuzss/combatnouveau#4]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

8.0.3

### Minimal Setup (Required)
Just CombatNouveau and Puzzlelib
⸺

### Notes (Required)

	#Format for every entry is "<namespace>:<path>,<amount>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. May use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*_shulker_box" to match all shulker boxes no matter of color.
	attack_speed_overrides = ["minecraft:iron_sword,8.0", "minecraft:diamond_sword,-1"]

Expected:
* ✅ Iron Sword to have +12 Attack Speed (Due Vanilla 4 + 8 Additional from mod)
* ❌ Diamond sword to have 3 Attack speed  (Due Vanilla 4 - 1 Attack speed from mod)

Actual result: 
```[23:29:11] [Server thread/WARN] [Puzzles Lib/]: Unable to parse entry minecraft:diamond_sword,-1
java.lang.IllegalStateException: Data -1.0 at index 0 from source entry minecraft:diamond_sword,-1 does not conform to filter
```
due filters defined at lines
https://github.com/Fuzss/combatnouveau/blob/main/1.20.4/Common/src/main/java/fuzs/combatnouveau/config/ServerConfig.java#L84-L88

This makes it impossible to make any kind of item slower than 4 (which is very quick already)
This filter seems pointless as Minecraft has no issues supporting negative attributes 
Screenshot example produced with give command
![image](https://github.com/Fuzss/combatnouveau/assets/3682284/92720e79-0bd2-48d1-8e32-f3d32d3011b0)

```/give @p diamond_sword{AttributeModifiers:[{AttributeName:"generic.attack_speed",Amount:-4,Slot:mainhand,Name:"generic.attack_speed",UUID:[I;-124123,789,13314,-1578]}]} 1```

### latest.log (Required)

https://mclo.gs/u4jG1nH

**Comment by Fuzss** [comment]
Thanks, fixed.
I've went ahead and completely removed the limit, although keep in mind that attributes in vanilla are limited to a certain range. Damage and attack speed both cannot go below 0. So this is only useful for removing the player base value, going below that will show correctly on the tooltip, but will be treated as setting the value to 0 by game mechanics.

**Comment by MelonCode** [comment]
Thank you!
