### ISSUE TITLE
[Bug]: hitbox size

### ISSUE THREAD

**Issue by Nitess** [Fuzss/combatnouveau#6]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

8.0.3 - 8.0.4 

### Minimal Setup (Required)

Yes

### Notes (Required)

`#This only affects targeting an entity, no collisions or whatsoever. Useful for hitting e.g. bats, rabbits, silverfish, fish, and most baby animals
min_hitbox_size = true`  breaks any resource warehouse that has item frames.
Apparently, increasing the hitbox also works on the frames
A banal wall of rotated double chests with frames cannot be opened

### latest.log (Required)

It is unlikely that a log is required for this problem

**Comment by Fuzss** [comment]
Thanks, fixed in latest version.
