### ISSUE TITLE
[Suggestion]: Release 1.19.2 Version

### ISSUE THREAD

**Issue by wtrflsh** [Fuzss/combatnouveau#7]
### Mod Loader (Optional)

Forge

### Minecraft Version(s) (Optional)

1.19.2

### Suggestion (Required)

I see you have a 1.19 version already created. Why is there no release for said version?

I tried building the folder myself, it did not succeed on my end tho, probably due to user error. 
```
Could not open cp_settings generic class cache for settings file 'X:\Downloads\combatnouveau-main\1.19.2\settings.gradle' (C:\Users\...\.gradle\caches\7.6\scripts\clsvq5oupataa5vjkjxfse8l3).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65
```
I would be more than grateful if you could offer a release for this version as well ^^

**Comment by Fuzss** [comment]
There is no 1.19 version, the folder in the main branch is basically empty. 
A port will be made when Puzzles Lib is backported from 1.20.4 which is now almost one year behind on 1.19.2.
