### ISSUE TITLE
[Bug]: Weapon attack reach does not work

### ISSUE THREAD

**Issue by Cirvel** [Fuzss/combatnouveau#8]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

CombatNouveau-v20.4.5-1.20.4-Fabric.jar

### Minimal Setup (Required)

Yes

### Notes (Required)

Swords, hoes, and tridents do not have the increased reach benefit as intended, they hit mobs just as far as an axe or by hand.

This is tested with the default generated config and in survival mode.

### latest.log (Required)

nil

**Comment by Fuzss** [comment]
Yeah, this is not implemented in 1.20.4 in fabric as the required library wasn’t updated. It’s back now in 1.21 and support for 1.20.4 has been dropped.
